//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emu5.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int editor_fontSize {
            get {
                return ((int)(this["editor_fontSize"]));
            }
            set {
                this["editor_fontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool editor_enableHighlighting {
            get {
                return ((bool)(this["editor_enableHighlighting"]));
            }
            set {
                this["editor_enableHighlighting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int editor_defaultTemplate {
            get {
                return ((int)(this["editor_defaultTemplate"]));
            }
            set {
                this["editor_defaultTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool emulator_clearMemoryMap {
            get {
                return ((bool)(this["emulator_clearMemoryMap"]));
            }
            set {
                this["emulator_clearMemoryMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool emulator_useIntegratedEcallHandler {
            get {
                return ((bool)(this["emulator_useIntegratedEcallHandler"]));
            }
            set {
                this["emulator_useIntegratedEcallHandler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4294963200")]
        public uint emulator_ecallBase {
            get {
                return ((uint)(this["emulator_ecallBase"]));
            }
            set {
                this["emulator_ecallBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfUnsignedInt xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <unsignedInt>0</unsignedInt>
  <unsignedInt>2684354559</unsignedInt>
  <unsignedInt>3221225472</unsignedInt>
  <unsignedInt>4294967295</unsignedInt>
</ArrayOfUnsignedInt>")]
        public uint[] memoryMap_memoryRanges {
            get {
                return ((uint[])(this["memoryMap_memoryRanges"]));
            }
            set {
                this["memoryMap_memoryRanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte memoryMap_uninitializedMemoryValue {
            get {
                return ((byte)(this["memoryMap_uninitializedMemoryValue"]));
            }
            set {
                this["memoryMap_uninitializedMemoryValue"] = value;
            }
        }
    }
}
